---
title: "ForestPlotACE151"
author: "Michael Andreae"
date: "December 8, 2015"
output: pdf_document
---

```{r, global_options, echo=FALSE}
suppressWarnings(library(knitr))
# set options
opts_chunk$set(fig.width=6, fig.height=4, fig.path='Figs/',
               echo=FALSE, warning=FALSE, message=FALSE)
eval_everything=FALSE
```


We are creating the Forest plot for the Illiac Crest Bone Granft Harvesting Bayesian analysis based on Dr. Johnson's graph for our JPain meta-analysis on cannabis for chronic neuropathic pain

```{r}
library(forestplot)
eval_everything=FALSE
```

# Example 

Example from <https://cran.r-project.org/web/packages/forestplot/vignettes/forestplot.html>

```{r, example, eval=eval_everything}
library(forestplot)
# Cochrane data from the 'rmeta'-package
cochrane_from_rmeta <- 
  structure(list(
    mean  = c(NA, NA, 0.578, 0.165, 0.246, 0.700, 0.348, 0.139, 1.017, NA, 0.531), 
    lower = c(NA, NA, 0.372, 0.018, 0.072, 0.333, 0.083, 0.016, 0.365, NA, 0.386),
    upper = c(NA, NA, 0.898, 1.517, 0.833, 1.474, 1.455, 1.209, 2.831, NA, 0.731)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -11L), 
    class = "data.frame")

tabletext<-cbind(
  c("", "Study", "Auckland", "Block", 
    "Doran", "Gamsu", "Morrison", "Papageorgiou", 
    "Tauesch", NA, "Summary"),
  c("Deaths", "(steroid)", "36", "1", 
    "4", "14", "3", "1", 
    "8", NA, NA),
  c("Deaths", "(placebo)", "60", "5", 
    "11", "20", "7", "7", 
    "10", NA, NA),
  c("", "OR", "0.58", "0.16", 
    "0.25", "0.70", "0.35", "0.14", 
    "1.02", NA, "0.53"))

forestplot(tabletext, 
           cochrane_from_rmeta,new_page = TRUE,
           is.summary=c(TRUE,TRUE,rep(FALSE,8),TRUE),
           clip=c(0.1,2.5), 
           xlog=TRUE, 
           col=fpColors(box="royalblue",line="darkblue", summary="royalblue"))
```

# Template Dr. Johnson

```{r, Johnson, eval=eval_everything}
forestplot(
  cbind(
    c('Study','','Abrams 07','','Ellis 09','','Ware 10','Ware 10',
      'Ware 10','','Wilsey 08','Wilsey 08','','Wilsey 13',
      'Wilsey 13','','Bayesian'),
      c('Dose','',96,'',96,'',2.5,6.3,9.4,'',19,34,'',9.0,18,'',''),
      c("Placebo",'',"6/25",'',"5/28",'',"3/22","","",'',"18/33",
        "",'',"11/38","","",""),
      c("Treat",'',"13/25",'',"13/28",'',"4/21","5/22","7/21",'',
        "24/36","22/33",'',"17/37","18/36","",""),
      c('Est. OR (CI)',NA, '3.43 (1.00,11.8)', NA, 
        '5.00 (1.10,22.9)',NA, '1.50 (0.25,8.98)',
        '3.00 (0.31,28.8)','5.00 (0.58,42.8)',NA,
        '2.67 (0.71,10.1)','3.50 (0.73,16.8)',NA,
        '2.50 (0.78,7.97)','3.67 (1.02,13.1)', NA, 
        '3.22 (1.59,7.24)')),
  (c(NA,NA,1.2327,NA,1.609,NA,.405,1.099,1.609,NA,.981,1.253,NA,.916,1.299,NA,1.169)),
  (c(NA,NA,0,NA,.091,NA,-1.38,-1.165,-.538,NA,-.346,-.319,NA,-.243,.023,NA,.462)),
  (c(NA,NA,2.4649,NA,3.13,NA,2.195,3.36,3.756,NA,2.308,2.824,NA,2.076,2.576,NA,1.986)),
  is.summary=c(T,T,F,T,F,T,F,F,F,T,F,F,T,F,F,T,T),
  main='Ignoring Dose',xlab='Odds Ratio',xlog=T,
  xlim=c(-1,exp(4)),
  xticks=c(.2,.5,1,2,5,10,20,40))
```

# Forest Plot for ACE 151

```{r, ACE151}
StudyNames <- c('Study','','Abrams 07','','Ellis 09','','Ware 10',
                'Ware 10','Ware 10','','Wilsey 08','Wilsey 08','',
                'Wilsey 13','Wilsey 13','','Bayesian')

FollowUp <- c('Follow up','',96,'',96,'',2.5,6.3,9.4,'',19,34,'',9.0,18,
              '','')
forestplot(
  cbind(
      StudyNames,
      FollowUp,
      c("Placebo",'',"6/25",'',"5/28",'',"3/22","","",'',"18/33",
        "",'',"11/38","","",""),
      c("Treat",'',"13/25",'',"13/28",'',"4/21","5/22","7/21",'',
        "24/36","22/33",'',"17/37","18/36","",""),
      c('Est. OR (CI)',NA, '3.43 (1.00,11.8)', NA, 
        '5.00 (1.10,22.9)',NA, '1.50 (0.25,8.98)',
        '3.00 (0.31,28.8)','5.00 (0.58,42.8)',NA,
        '2.67 (0.71,10.1)','3.50 (0.73,16.8)',NA,
        '2.50 (0.78,7.97)','3.67 (1.02,13.1)', NA, 
        '3.22 (1.59,7.24)')),
  (c(NA,NA,1.2327,NA,1.609,NA,.405,1.099,1.609,NA,.981,1.253,NA,.916,1.299,NA,1.169)),
  (c(NA,NA,0,NA,.091,NA,-1.38,-1.165,-.538,NA,-.346,-.319,NA,-.243,.023,NA,.462)),
  (c(NA,NA,2.4649,NA,3.13,NA,2.195,3.36,3.756,NA,2.308,2.824,NA,2.076,2.576,NA,1.986)),
  is.summary=c(T,T,F,T,F,T,F,F,F,T,F,F,T,F,F,T,T),
  main='Ignoring Dose',xlab='Odds Ratio',xlog=T,
  xlim=c(-1,exp(4)),
  xticks=c(.2,.5,1,2,5,10,20,40))
```